---
- name: Add git-core gpg from a keyserver
  ansible.builtin.get_url:
    url: https://keyserver.ubuntu.com/pks/lookup?op=get&search=0xe363c90f8f1b6217
    dest: /etc/apt/trusted.gpg.d/git-core.asc
    mode: "644"

- name: Add git-core repository
  ansible.builtin.apt_repository:
    repo: >
      deb [arch={{ arch_mapping[ansible_facts['architecture']] }} signed-by=/etc/apt/trusted.gpg.d/git-core.asc]
      https://ppa.launchpadcontent.net/git-core/ppa/ubuntu {{ ansible_facts['distribution_release'] }} main
    state: present

- name: Do apt upgrade
  ansible.builtin.apt:
    upgrade: safe
    update_cache: true

- name: Install packages dependencies
  ansible.builtin.package:
    name:
      - nano
      - wget
      - build-essential
      - chrony
      - curl
      - openssh-server
      - ca-certificates
      - tzdata
      - sshpass
      - git
      - zip
      - unzip
    state: present

- name: Set application list for installation
  ansible.builtin.set_fact:
    applications:
      - name: yq
        version: 4.52.5
        url: https://github.com/mikefarah/yq/releases/download/v#application_version#/yq_linux_amd64
        binary_files:
          - name: yq
            file: yq_linux_amd64

      - name: jq
        version: 1.8.1
        url: https://github.com/jqlang/jq/releases/download/jq-#application_version#/jq-linux-amd64
        binary_files:
          - name: jq
            file: jq-linux-amd64

      - name: nodejs
        version: 24.14.1
        url: https://nodejs.org/dist/v#application_version#/node-v#application_version#-linux-x64.tar.xz
        binary_files:
          - name: corepack
            file: bin/corepack

          - name: node
            file: bin/node

          - name: npm
            file: bin/npm

          - name: npx
            file: bin/npx
        is_archive: true

- name: Install applications
  ansible.builtin.include_tasks:
    file: install_application.yml
  loop: "{{ applications }}"
  loop_control:
    label: "{{ item.name }}"
