---
- name: Create the cinder user
  ansible.builtin.command:
    cmd: openstack user create --domain default --password '{{ os_cinder_password }}' cinder
  register: create_cinder_user
  changed_when: create_cinder_user.stdout is defined and "password_expires_at" in create_cinder_user.stdout
  failed_when: create_cinder_user.rc != 0 and "ConflictException" not in create_cinder_user.stderr

- name: Add the admin role to the cinder user and service project
  ansible.builtin.command:
    cmd: openstack role add --project service --user cinder admin
  changed_when: false

- name: Check service entity for cinder
  ansible.builtin.shell:
    cmd: openstack service show volumev3 || true
    executable: /bin/bash
  register: service_cinder
  changed_when: false

- name: Create the cinder service entity
  ansible.builtin.command:
    cmd: openstack service create --name cinderv3 --description "OpenStack Block Storage" volumev3
  when: service_cinder.stderr is defined and "No service with a type, name or ID" in service_cinder.stderr
  changed_when: true

- name: Check public cinder service API endpoints
  ansible.builtin.shell:
    cmd: |
      set -o pipefail #
      openstack endpoint list | grep -E 'RegionOne.*.cinderv3.*.volumev3.*.public.*.http://{{ controller01_host_addr }}:8776/v3' || true
    executable: /bin/bash
  register: public_endpoint
  changed_when: false

- name: Create public cinder service API endpoints
  ansible.builtin.command:
    cmd: openstack endpoint create --region RegionOne volumev3 public http://{{ controller01_host_addr }}:8776/v3/%\(project_id\)s
  when: public_endpoint.stdout is defined and public_endpoint.stdout == ""
  changed_when: true

- name: Check internal cinder service API endpoints
  ansible.builtin.shell:
    cmd: |
      set -o pipefail #
      openstack endpoint list | grep -E 'RegionOne.*.cinderv3.*.volumev3.*.internal.*.http://{{ controller01_host_addr }}:8776/v3' || true
    executable: /bin/bash
  register: internal_endpoint
  changed_when: false

- name: Create internal cinder service API endpoints
  ansible.builtin.command:
    cmd: openstack endpoint create --region RegionOne volumev3 internal http://{{ controller01_host_addr }}:8776/v3/%\(project_id\)s
  when: internal_endpoint.stdout is defined and internal_endpoint.stdout == ""
  changed_when: true

- name: Check admin cinder service API endpoints
  ansible.builtin.shell:
    cmd: |
      set -o pipefail #
      openstack endpoint list | grep -E 'RegionOne.*.cinderv3.*.volumev3.*.admin.*.http://{{ controller01_host_addr }}:8776/v3' || true
    executable: /bin/bash
  register: admin_endpoint
  changed_when: false

- name: Create admin cinder service API endpoints
  ansible.builtin.command:
    cmd: openstack endpoint create --region RegionOne volumev3 admin http://{{ controller01_host_addr }}:8776/v3/%\(project_id\)s
  when: admin_endpoint.stdout is defined and admin_endpoint.stdout == ""
  changed_when: true
