---
mariadb_password: platformpass
keystone_password: platformpass
glance_password: platformpass
os_glance_password: platformpass
placement_password: platformpass
nova_password: platformpass
neutron_password: platformpass
octavia_password: platformpass
