---
- name: Install dependencies
  ansible.builtin.include_tasks:
    file: dependencies.yml

- name: Apply Ceph public key
  ansible.builtin.blockinfile:
    path: /root/.ssh/authorized_keys
    append_newline: true
    prepend_newline: true
    block: "{{ lookup('ansible.builtin.file', ceph_pub_key_fetch_path) }}"
    insertafter: EOF

- name: Prepare disk
  ansible.builtin.shell:
    cmd: |
      pvremove -ff /dev/{{ device_name }}
      wipefs -a /dev/{{ device_name }}
      sgdisk --zap-all /dev/{{ device_name }}
      DISK=/dev/{{ device_name }}
      dd if=/dev/zero of=$DISK bs=1M count=100 oflag=direct,dsync
      SIZE=$(blockdev --getsz $DISK)
      END=$((SIZE - 1024))
      dd if=/dev/zero of=$DISK bs=512 seek=$END count=1024 oflag=direct,dsync
    executable: /bin/bash
  changed_when: false
