---
- name: Start and enable all Neutron services
  ansible.builtin.service:
    name: "{{ item }}"
    state: restarted
    enabled: true
  loop:
    - neutron-openvswitch-agent
    - neutron-dhcp-agent
    - neutron-metadata-agent
