# -*- mode: ruby -*-
# vi: set ft=ruby :

require_relative "../base"

Vagrant.configure("2") do |config|
  cmds = <<-SHELL
    echo Execute provision
  SHELL

  setup_vm("local/nodes.yml", config, "ubuntu_24_base", cmds)
end