# -*- mode: ruby -*-
# vi: set ft=ruby :

require_relative "../base"

Vagrant.configure("2") do |config|
  cmds = <<-SHELL
    apt install chrony -y
    systemctl enable chronyd
    systemctl start chronyd
    add-apt-repository -y cloud-archive:dalmatian
    apt update
    apt upgrade -y
    apt install -y nova-compute python3-openstackclient
  SHELL

  setup_vm("nodes", config, "ubuntu_24_base", cmds)
end