---
- name: Install Docker on Ubuntu distributions
  when: "'ubuntu' in (ansible_facts['distribution'] | lower)"
  block:
    - name: Install Docker on Ubuntu distributions
      ansible.builtin.debug:
        msg: The OS distribution is Ubuntu, proceeding with Ubuntu installation

    - name: Install Docker repository
      ansible.builtin.include_role:
        name: common
        tasks_from: install_package_repository
      vars:
        repository_source_name: docker
        repository_uri: https://download.docker.com/linux/ubuntu
        repository_key_uri: https://download.docker.com/linux/ubuntu/gpg
        repository_key_filename: docker.asc

    - name: Remove any other packages which are potentially conflicting
      ansible.builtin.package:
        name:
          - docker.io
          - docker-doc
          - docker-compose
          - docker-compose-v2
          - podman-docker
          - containerd
          - runc
        state: absent

- name: Install Docker on RHEL-based distributions
  when: "'redhat' in (ansible_facts['os_family'] | lower)"
  block:
    - name: Install Docker on RHEL-based distributions
      ansible.builtin.debug:
        msg: The OS distribution is RHEL-based, proceeding with RHEL-based installation

    - name: Install Docker repository
      ansible.builtin.include_role:
        name: common
        tasks_from: install_package_repository
      vars:
        repository_source_name: docker-ce
        repository_uri: https://download.docker.com/linux/centos/{{ ansible_facts['distribution_major_version'] }}/x86_64/stable/
        repository_key_uri: https://download.docker.com/linux/centos/gpg

    - name: Remove any other packages which are potentially conflicting
      ansible.builtin.package:
        name:
          - docker
          - docker-client
          - docker-client-latest
          - docker-common
          - docker-latest
          - docker-latest-logrotate
          - docker-logrotate
          - docker-engine
          - podman
          - runc
        state: absent

- name: Install Docker and related packages
  ansible.builtin.package:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: present
  any_errors_fatal: true

- name: Add Docker group
  ansible.builtin.group:
    name: docker
    state: present

- name: Add user to Docker group
  ansible.builtin.user:
    name: "{{ ansible_user }}"
    password: "{{ ansible_password | password_hash('sha512', 'mysecretsalt') }}"
    groups: docker
    append: true

- name: Configure http proxy
  ansible.builtin.include_tasks:
    file: configure_http_proxy.yml
