---
lab:
  vars:
    root_dir: "{{ lookup('ansible.builtin.env', 'ROOT_DIR') | default(playbook_dir | dirname | dirname, true) }}"
    target_env: local
  children:
    assistant:
      hosts:
        assistant01:
          ansible_host: "{{ assistant01.mgmtnet_ip_address }}"
    ai_ops_host_observers:
      hosts:
        controller01:
          ansible_host: "{{ controller01.mgmtnet_ip_address }}"
        compute01:
          ansible_host: "{{ compute01.mgmtnet_ip_address }}"
        compute02:
          ansible_host: "{{ compute02.mgmtnet_ip_address }}"
