---
- name: Deploy and setup Ceph monitor and manager
  hosts: ceph
  become: true
  vars_files:
    - "{{ root_dir ~ '/inventories/' ~ target_env ~ '/nodes.yml' }}"
  roles:
    - role: monitor_manager
