---
- name: Copy Cinder keyring
  ansible.builtin.copy:
    src: "{{ cinder_keyring_path }}"
    dest: /etc/ceph/ceph.client.cinder.keyring
    owner: nova
    group: nova
    mode: "644"

- name: Copy Libvirt secret xml file
  ansible.builtin.template:
    src: nova_compute_libvirt_secret.xml.j2
    dest: /tmp/libvirt_secret.xml
    mode: "644"

- name: Create Libvirt secret
  ansible.builtin.command:
    cmd: virsh secret-define --file /tmp/libvirt_secret.xml
  register: virsh_secret_define
  changed_when: virsh_secret_define.stdout is defined and 'created' in virsh_secret_define.stdout

- name: Set Libvirt secret value
  ansible.builtin.shell:
    cmd: |
      set -o pipefail #
      virsh secret-set-value --secret {{ libvirt_secret_uuid }} --base64 $(cat /etc/ceph/ceph.client.cinder.keyring | grep key | awk '{print $NF}')
    executable: /bin/bash
  register: virsh_secret_set_value
  changed_when: virsh_secret_set_value.stdout is defined and 'value set' in virsh_secret_set_value.stdout

- name: Reconfigure nova.conf - set libvirt
  ansible.builtin.replace:
    path: /etc/nova/nova.conf
    regexp: "^\\[libvirt\\](\n(.*))*?\n*(# Libvirt options allows cloud administrator).*"
    replace: "{{ lookup('ansible.builtin.template', 'nova_compute_libvirt.conf.j2') }}"

- name: Start and enable Nova compute
  ansible.builtin.service:
    name: nova-compute
    state: restarted
    enabled: true
