---
- name: Configure the system settings and stuff
  ansible.builtin.include_tasks:
    file: configure.yml

- name: Install OpenStack exporter
  ansible.builtin.include_role:
    name: common
    tasks_from: install_archived_package
  vars:
    download_url: "{{ openstack_exporter_download_url }}/v{{ openstack_exporter_version }}/openstack-exporter_{{ openstack_exporter_version }}_linux_amd64.tar.gz"
    download_to_path: /tmp/openstack_exporter.tar.gz
    no_strip: true
    file_owner: "{{ ansible_user }}"
    home_path: "{{ openstack_exporter_home }}"
    config_file: openstack_clouds.yml
    service_file: prometheus_openstack_exporter.service

- name: Install Mariadb exporter
  ansible.builtin.include_role:
    name: common
    tasks_from: install_archived_package
  vars:
    download_url: "{{ mysqld_exporter_download_url }}/v{{ mysqld_exporter_version }}/mysqld_exporter-{{ mysqld_exporter_version }}.linux-amd64.tar.gz"
    download_to_path: /tmp/mysqld_exporter.tar.gz
    file_owner: "{{ ansible_user }}"
    home_path: "{{ mysqld_exporter_home }}"
    config_file: mariadb_exporter.cnf
    service_file: prometheus_mariadb_exporter.service

- name: Start services
  ansible.builtin.systemd_service:
    name: "{{ item }}"
    enabled: true
    state: restarted
    daemon_reload: true
  loop:
    - prometheus_openstack_exporter
    - prometheus_mariadb_exporter
