---
- name: Check the service project
  ansible.builtin.shell:
    cmd: openstack project show service
    executable: /bin/bash
  register: service_project
  changed_when: false
  failed_when:
    - service_project.rc != 0
    - service_project.stderr is defined
    - "'no project found' not in (service_project.stderr | lower)"

- name: Create the service project
  ansible.builtin.command:
    cmd: openstack project create --domain default --description "Service Project" service
  when: service_project.stderr is defined and 'no project found' in (service_project.stderr | lower)
  changed_when: true
