---
- name: Deploy and setup OpenStack dependencies
  hosts: all
  become: true
  vars_files:
    - "{{ var_file_path }}"
  roles:
    - role: common

    - role: ceph_common_vars
      when: ceph_enabled is defined and ceph_enabled

    - role: ceph
      when: ceph_enabled is defined and ceph_enabled
