---
ansible_connection: ssh
ansible_ssh_common_args: -o "UserKnownHostsFile=/dev/null" -o StrictHostKeyChecking=no -o "PubkeyAuthentication=no"

ai_ops_assistant_keystone_endpoint: "http://192.168.121.5:5000/v3"
