---
mysqld_exporter_download_url: https://github.com/prometheus/mysqld_exporter/releases/download
mysqld_exporter_version: 0.18.0
mysqld_exporter_home: /opt/mysqld_exporter

openstack_exporter_download_url: https://github.com/openstack-exporter/openstack-exporter/releases/download
openstack_exporter_version: 1.8.0-alpha
openstack_exporter_home: /opt/openstack_exporter
