# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  base_image_name = ENV["BASE_IMAGE_NAME"]
  if base_image_name.nil?
    puts ">>>>> BASE_IMAGE_NAME need to be provided <<<<<"; \
    puts "Add BASE_IMAGE_NAME=this_name to the command"; \
    exit 1
  end

  config.ssh.username = "vagrant"
  config.ssh.password = "vagrant"
  config.vm.define base_image_name do |d|
    d.vm.synced_folder ".", "/vagrant", disabled: true
  end

  if base_image_name == "ubuntu_24"
    config.vm.box = "bento/ubuntu-24.04"
    config.vm.box_version = "202508.03.0"
    config.vm.provision "shell", inline: <<-SHELL
      sudo apt update
      DEBIAN_FRONTEND=noninteractive apt -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" upgrade -y
      sudo update-grub
      sudo apt install qemu-guest-agent gcc cloud-init -y
    SHELL
  else
    puts ">>>>> BASE_IMAGE_NAME: #{base_image_name} is not available <<<<<"; \
    exit 1
  end
end
