---
- name: Check service entity for the component
  ansible.builtin.shell:
    cmd: openstack service show {{ service.name }}
    executable: /bin/bash
  register: service_component
  changed_when: false
  failed_when:
    - service_component.rc != 0
    - service_component.stderr is defined
    - "'no service with a type, name or id' not in (service_component.stderr | lower)"

- name: Create the component service entity
  ansible.builtin.command:
    cmd: openstack service create --name {{ os_component_name }} --description "{{ service.description }}" {{ service.name }}
  when: service_component.stderr is defined and 'no service with a type, name or id' in (service_component.stderr | lower)
  changed_when: true
