---
- name: Add OpenStack repository {{ openstack_repo }}
  ansible.builtin.command:
    cmd: add-apt-repository -y {{ openstack_repo }}
  register: add_repo_result
  changed_when: add_repo_result.stdout is defined and 'Found existing' not in add_repo_result.stdout

- name: Do apt upgrade
  ansible.builtin.apt:
    upgrade: full
    update_cache: true

- name: Ensure all the packages are installed already
  ansible.builtin.package:
    name:
      - chrony
      - python3-openstackclient
      - bridge-utils
    state: present
