---
- name: Add other nodes to other cluster
  ansible.builtin.command:
    cmd: ceph orch host add {{ item }} {{ node_vars.mgmtnet_ip_address }}
  vars:
    node_vars: "{{ lookup('ansible.builtin.vars', item) }}"
  loop: "{{ groups['ceph_common'] }}"
  changed_when: false

- name: Wait hosts and its devices to be ready
  ansible.builtin.shell:
    cmd: |
      set -o pipefail #
      until sudo ceph orch device ls | grep -P '^(?=.*{{ item }})(?=.*/dev/{{ device_name }})'; do
        sleep 1
      done
    executable: /bin/bash
  loop: "{{ groups['ceph_common'] }}"
  changed_when: false

- name: Place MON
  ansible.builtin.command:
    cmd: ceph orch apply mon --placement="{{ mon_count }}"
  changed_when: false

- name: Place MGR
  ansible.builtin.command:
    cmd: ceph orch apply mgr --placement="{{ mgr_count }}"
  changed_when: false
