---
- name: Setup AI-OPS assistant runtime
  hosts: assistant
  become: true
  vars_files:
    - "{{ root_dir ~ '/inventories/' ~ target_env ~ '/nodes.yml' }}"
  roles:
    - role: common
      vars:
        enable_firewall: true
        additional_packages:
          - python3-pip
          - python3-venv

    - role: assistant_runtime
