---
ansible_user: ansible_sys_user
ansible_password: ansible_sys_password
ansible_sudo_pass: ansible_sys_password

rabbitmq_password: platformpass
os_keystone_password: platformpass
os_placement_password: platformpass
os_nova_password: platformpass
os_neutron_password: platformpass
cinder_password: platformpass
os_cinder_password: platformpass
metadata_secret: platformpass
os_octavia_password: platformpass
