name: Run ansible sanity test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11", "3.12"]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r requirements.txt

    - name: Run Ansible sanity test lint
      run: |
        source circ
        ansible-lint --fix --config-file ./.ansible-lint ansible/* inventories/*

    - name: Run Ansible inventory variable validation test using molecule - Openstack
      run: |
        source circ
        make validate-openstack

    - name: Run Ansible inventory variable validation test using molecule - Ceph
      run: |
        source circ
        make validate-ceph